const MODEL_EVENTS = {
  VALUE_CHANGED: 'VALUE_CHANGED',
  VALUE_CHANGED_BY_CLICK: 'VALUE_CHANGED_BY_CLICK',
};

const SLIDER_EVENTS = {
  VALUE_START_CHANGE: 'VALUE_START_CHANGE',
  DATA_COLLECTED: 'DATA_COLLECTED',
  VALUE_CHANGED: 'VALUE_CHANGED',
  SCALE_CLICKED: ' SCALE_CLICKED',
  VALUE_CHANGED_BY_CLICK: 'VALUE_CHANGED_BY_CLICK',
};

export { MODEL_EVENTS, SLIDER_EVENTS };
