const MODEL_EVENTS = {
  VALUE_CHANGED: 'VALUE_CHANGED',
}

const SLIDER_EVENTS = {
  VALUE_START_CHANGE: 'VALUE_START_CHANGE',
  DATA_COLLECTED: 'DATA_COLLECTED',
  VALUE_CHANGED: 'VALUE_CHANGED',
}

export { MODEL_EVENTS, SLIDER_EVENTS }